//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeMeHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADInformation
    {
        public int Id { get; set; }
        public string sAMAccountNAme { get; set; }
        public string displayName { get; set; }
        public string mail { get; set; }
        public string title { get; set; }
        public string telephoneNumber { get; set; }
        public string givenName { get; set; }
        public string sn { get; set; }
        public string company { get; set; }
        public string wwWHomePage { get; set; }
        public string mobile { get; set; }
        public string cn { get; set; }
        public string APPUSERNAME { get; set; }
    }
}
