//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeMeHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicConf
    {
        public int Id { get; set; }
        public bool FileSystemUpload { get; set; }
        public bool ADActive { get; set; }
        public bool EmailConfirmation { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public string AppAdmin { get; set; }
        public string BackAdmin { get; set; }
        public string LDAPConn { get; set; }
        public string LDAPPath { get; set; }
        public string ManageHREmail { get; set; }
        public string ManageHREmailPass { get; set; }
        public string SMTPHost { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public Nullable<bool> EnableSSL { get; set; }
    }
}
