//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeMeHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public string MsgID { get; set; }
        public Nullable<int> MsgSequence { get; set; }
        public string SenderEmail { get; set; }
        public string RecipientEmail { get; set; }
    }
}
