//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeMeHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileDetail
    {
        public System.Guid Id { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
