//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeMeHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualAssignmentHistory
    {
        public int Id { get; set; }
        public int AssignedTo { get; set; }
        public string AssignedBy { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public Nullable<int> ServiceRequest { get; set; }
    
        public virtual ServiceRequest ServiceRequest1 { get; set; }
        public virtual Member Member { get; set; }
    }
}
