//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeMeHR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServeMeHREntities : DbContext
    {
        public ServeMeHREntities()
            : base("name=ServeMeHREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADInformation> ADInformations { get; set; }
        public virtual DbSet<ApplicConf> ApplicConfs { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<FileDetail> FileDetails { get; set; }
        public virtual DbSet<IndividualAssignmentHistory> IndividualAssignmentHistories { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<RequestType> RequestTypes { get; set; }
        public virtual DbSet<RequestTypeStep> RequestTypeSteps { get; set; }
        public virtual DbSet<ServiceRequestNote> ServiceRequestNotes { get; set; }
        public virtual DbSet<ServiceRequest> ServiceRequests { get; set; }
        public virtual DbSet<StatusSet> StatusSets { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
        public virtual DbSet<StepHistory> StepHistories { get; set; }
        public virtual DbSet<TeamAssignmentHistory> TeamAssignmentHistories { get; set; }
        public virtual DbSet<TeamMember> TeamMembers { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
