//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeMeHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.FileDetails = new HashSet<FileDetail>();
            this.IndividualAssignmentHistories = new HashSet<IndividualAssignmentHistory>();
            this.ServiceRequestNotes = new HashSet<ServiceRequestNote>();
            this.StepHistories = new HashSet<StepHistory>();
            this.TeamAssignmentHistories = new HashSet<TeamAssignmentHistory>();
        }
    
        public int Id { get; set; }
        public string RequestHeading { get; set; }
        public string RequestDescription { get; set; }
        public string RequestorID { get; set; }
        public string RequestorFirstName { get; set; }
        public string RequestorLastName { get; set; }
        public string RequestorPhone { get; set; }
        public string RequestorEmail { get; set; }
        public Nullable<System.DateTime> DateTimeSubmitted { get; set; }
        public Nullable<System.DateTime> DateTimeStarted { get; set; }
        public Nullable<System.DateTime> DateTimeCompleted { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> RequestType { get; set; }
        public Nullable<int> RequestTypeStep { get; set; }
        public Nullable<int> Member { get; set; }
        public int Status { get; set; }
        public int Team { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileDetail> FileDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualAssignmentHistory> IndividualAssignmentHistories { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Member Member2 { get; set; }
        public virtual Priority Priority1 { get; set; }
        public virtual Priority Priority2 { get; set; }
        public virtual RequestType RequestType1 { get; set; }
        public virtual RequestType RequestType2 { get; set; }
        public virtual RequestTypeStep RequestTypeStep1 { get; set; }
        public virtual RequestTypeStep RequestTypeStep2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestNote> ServiceRequestNotes { get; set; }
        public virtual StatusSet StatusSet { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual StatusSet StatusSet1 { get; set; }
        public virtual Team Team2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StepHistory> StepHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamAssignmentHistory> TeamAssignmentHistories { get; set; }
    }
}
