//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeMeHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestNote
    {
        public int Id { get; set; }
        public string NoteDescription { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string WrittenBy { get; set; }
        public Nullable<int> ServiceRequest { get; set; }
    
        public virtual ServiceRequest ServiceRequest1 { get; set; }
    }
}
